// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//Note from author of this project: Below is a pre-provided comment from using
//FlutterFire CLI.
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  //returns the FirebaseOptions for the currentPlatform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //Web FirebaseOptions
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh6-v_Es-2lzOza_yLmsQu_mkb-3FQOgc',
    appId: '1:1026053522641:web:fd9695400a1e6bc024f1f0',
    messagingSenderId: '1026053522641',
    projectId: 'groupfly-a90ae',
    authDomain: 'groupfly-a90ae.firebaseapp.com',
    storageBucket: 'groupfly-a90ae.appspot.com',
    measurementId: 'G-RYVM2H3TF5',
  );

  //Android FirebaseOptions
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFc6thmysVQpndomi9dWazT1CpRJ_5Cfc',
    appId: '1:1026053522641:android:e00c0fdb85c9084224f1f0',
    messagingSenderId: '1026053522641',
    projectId: 'groupfly-a90ae',
    storageBucket: 'groupfly-a90ae.appspot.com',
  );

  //iOS FirebaseOptions
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ-2or2qLcNRmVmNlhpc60ak0AfBxTIzs',
    appId: '1:1026053522641:ios:b7f959abf61d371f24f1f0',
    messagingSenderId: '1026053522641',
    projectId: 'groupfly-a90ae',
    storageBucket: 'groupfly-a90ae.appspot.com',
    iosBundleId: 'com.example.groupflyProject',
  );
}
